### ISSUE TITLE
NoSuchMethodError: The method 'map' was called on null.

### ISSUE THREAD

**Issue by niypoo** [RevenueCat/purchases-flutter#111]
**Describe the bug**
everything working great until I update package form `1.1.1` to `1.3.1` then this error show to me when any package event trigger like

```
PurchaserInfo purchaserInfo = await Purchases.getPurchaserInfo();
```

```

flutter: NoSuchMethodError: The method 'map' was called on null.
Receiver: null
Tried calling: map<Transaction>(Closure: (dynamic) => Transaction)
flutter:
#0      Object.noSuchMethod  (dart:core-patch/object_patch.dart:51:5)
#1      new PurchaserInfo.fromJson 
package:purchases_flutter/purchaser_info_wrapper.dart:79
#2      Purchases.getPurchaserInfo 
package:purchases_flutter/purchases_flutter.dart:276
<asynchronous suspension>
#3      InAppPurchaseService.checkSubscriptionStoreState 
package:project/services/inAppPurchase.service.dart:96
#4      SubscriptionController.checkEntitlementStateNotStream 
package: project/controllers/subscription.controller.dart:26
#5      SubscriptionController.listenOnPurchaseChanges 
package: project/controllers/subscription.controller.dart:20
#6      new SubscriptionController 
package: project/controllers/subscription.controller.dart:14
#7      InitializationBiniding.dependencies 

``` 

```
await Purchases.restoreTransactions();
```

```

flutter: ----------------FIREBASE CRASHLYTICS----------------
flutter: PlatformException(9, The receipt is missing., {code: 9, message: The receipt is missing., readable_error_code: MISSING_RECEIPT_FILE, readableErrorCode: MISSING_RECEIPT_FILE}, null)
flutter:

```

I'm working on simulator iOS with 
```
Flutter 1.22.0 • channel stable • https://github.com/flutter/flutter.git
Framework • revision d408d302e2 (12 days ago) • 2020-09-29 11:49:17 -0700
Engine • revision 5babba6c4d
Tools • Dart 2.10.0
```

**Comment by rkotzy** [comment]
Are you able to provide debug logs that reproduce this? https://docs.revenuecat.com/docs/debugging

**Comment by niypoo** [comment]
I'm already set debug true.

```


flutter: ----------------FIREBASE CRASHLYTICS----------------
flutter: NoSuchMethodError: The method 'map' was called on null.
Receiver: null
Tried calling: map<Transaction>(Closure: (dynamic) => Transaction)
flutter:
#0      Object.noSuchMethod  (dart:core-patch/object_patch.dart:51:5)
#1      new PurchaserInfo.fromJson 
package:purchases_flutter/purchaser_info_wrapper.dart:79
#2      Purchases.getPurchaserInfo 
package:purchases_flutter/purchases_flutter.dart:276
<asynchronous suspension>
#3      InAppPurchaseService.checkSubscriptionStoreState 
package:app/services/inAppPurchase.service.dart:96
#4      SubscriptionController.checkEntitlementStateNotStream 
package: app/controllers/subscription.controller.dart:26
#5      SubscriptionController.listenOnPurchaseChanges 
package: app/controllers/subscription.controller.dart:20
#6      new SubscriptionController 
package: app/controllers/subscription.controller.dart:14
#7      InitializationBiniding.dependencies 
package: app/bindings/initialization.binding.dart:11
#8      GetMaterialApp.build.<anonymous closure> 
package:get/…/root/root_widget.dart:224
#9      _GetBuilderState.initState 
package:get/…/simple/get_state.dart:168
#10     StatefulElement._firstBuild 
package:flutter/…/widgets/framework.dart:4765
#11     ComponentElement.mount 
package:flutter/…/widgets/framework.dart:4601
#12     Element.inflateWidget 
package:flutter/…/widgets/framework.dart:3569
#13     Element.updateChild 
package:flutter/…/widgets/framework.dart:3327
#14     ComponentElement.performRebuild 
package:flutter/…/widgets/framework.dart:4652
#15     Element.rebuild 
package:flutter/…/widgets/framework.dart:4343
#16     ComponentElement._firstBuild 
package:flutter/…/widgets/framework.dart:4606
#17     ComponentElement.mount 
package:flutter/…/widgets/framework.dart:4601
#18     Element.inflateWidget 
package:flutter/…/widgets/framework.dart:3569
#19     Element.updateChild 
package:flutter/…/widgets/framework.dart:3327
#20     ComponentElement.performRebuild 
package:flutter/…/widgets/framework.dart:4652
#21     Element.rebuild 
package:flutter/…/widgets/framework.dart:4343
#22     ComponentElement._firstBuild 
package:flutter/…/widgets/framework.dart:4606
#23     ComponentElement.mount 
package:flutter/…/widgets/framework.dart:4601
#24     Element.inflateWidget 
package:flutter/…/widgets/framework.dart:3569
#25     Element.updateChild 
package:flutter/…/widgets/framework.dart:3327
#26     ComponentElement.performRebuild 
package:flutter/…/widgets/framework.dart:4652
#27     Element.rebuild 
package:flutter/…/widgets/framework.dart:4343
#28     ComponentElement._firstBuild 
package:flutter/…/widgets/framework.dart:4606
#29     ComponentElement.mount 
package:flutter/…/widgets/framework.dart:4601
#30     Element.inflateWidget 
package:flutter/…/widgets/framework.dart:3569
#31     Element.updateChild 
package:flutter/…/widgets/framework.dart:3327
#32     ComponentElement.performRebuild 
package:flutter/…/widgets/framework.dart:4652
#33     Element.rebuild 
package:flutter/…/widgets/framework.dart:4343
#34     ComponentElement._firstBuild 
package:flutter/…/widgets/framework.dart:4606
#35     ComponentElement.mount 
package:flutter/…/widgets/framework.dart:4601
#36     Element.inflateWidget 
package:flutter/…/widgets/framework.dart:3569
#37     Element.updateChild 
package:flutter/…/widgets/framework.dart:3327
#38     ComponentElement.performRebuild 
package:flutter/…/widgets/framework.dart:4652
#39     StatefulElement.performRebuild 
package:flutter/…/widgets/framework.dart:4800
#40     Element.rebuild 
package:flutter/…/widgets/framework.dart:4343
#41     ComponentElement._firstBuild 
package:flutter/…/widgets/framework.dart:4606
#42     StatefulElement._firstBuild 
package:flutter/…/widgets/framework.dart:4791
#43     ComponentElement.mount 
package:flutter/…/widgets/framework.dart:4601
#44     Element.inflateWidget 
package:flutter/…/widgets/framework.dart:3569
#45     Element.updateChild 
package:flutter/…/widgets/framework.dart:3327



```

**Comment by vegaro** [comment]
Hi @niypoo 

I tried upgrading our sample project from 1.1.1 to 1.3.1 and I can't seem to reproduce this. Can you share the logs with us? To set them up do:

```
    await Purchases.setDebugLogsEnabled(true);
```

Before your setup call

Looks like what you shared is just the stacktrace of the error.

Thanks!

**Comment by aboedo** [comment]
I'm closing this ticket due to inactivity, but do let us know if you're still facing issues with this @niypoo

**Comment by balamurugesan1** [comment]
I am also facing this same issue.
any solutions?

**Comment by beylmk** [comment]
@balamurugesan1 could you please provide steps to reproduce and debug logs?

call `await Purchases.setDebugLogsEnabled(true);` before your setup call to enable the debug logs.

**Comment by aboedo** [comment]
I'm closing this ticket due to inactivity, feel free to open up a new ticket if you're running into this

**Comment by AliPunjabi** [comment]
I am facing the same issue.
steps to reproduce:
1- make an api call function http
2- create model of search movies api from tmdb
3- create model using product creator (https://quicktype.io/)

my flutter doctor report

[✓] Flutter (Channel stable, 2.8.0, on macOS 12.1 21C52 darwin-x64, locale
    en-US)
    • Flutter version 2.8.0 at /Users/apple/Documents/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision cf44000065 (3 months ago), 2021-12-08 14:06:50 -0800
    • Engine revision 40a99c5951
    • Dart version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/apple/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.63.2)
    • VS Code at /Users/apple/Downloads/Visual Studio Code.app/Contents
    • Flutter extension version 3.34.0

[✓] Connected device (2 available)
    • iPhone 13 (mobile) • E92B7BC9-E028-4A01-B554-CD7F0701D5C9 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-15-2 (simulator)
    • Chrome (web)       • chrome                               • web-javascript
      • Google Chrome 98.0.4758.109

• No issues found!
