### ISSUE TITLE
App crashes on Android when using flutter_genius_scan plugin together

### ISSUE THREAD

**Issue by jamesbrian0323** [RevenueCat/purchases-flutter#117]
**Describe the bug**
App crashes when I use this plugin with flutter_genius_scan (https://pub.dev/packages/flutter_genius_scan) on my Android Phone.
When I call genius SDK then app crashes, and if I remove the dependency from pubspec.yaml then it works well.
But on iPhone, it works well.

Error is like below:

```
AndroidRuntime(26804): Shutting down VM
E/AndroidRuntime(26804): FATAL EXCEPTION: main
E/AndroidRuntime(26804): Process: com.example.proj, PID: 23652
E/AndroidRuntime(26804): java.lang.NoSuchMethodError: No static method saveAttributeDataForStyleable(Landroid/view/View;Landroid/content/Context;[ILandroid/util/AttributeSet;Landroid/content/res/TypedArray;II)V in class Landroidx/core/view/ViewCompat; or its super classes (declaration of 'androidx.core.view.ViewCompat' appears in /data/app/com.example.proj-DTecE840qwF9BP3aeG34Mg==/base.apk)
E/AndroidRuntime(26804): 	at androidx.appcompat.widget.AppCompatBackgroundHelper.loadFromAttributes(AppCompatBackgroundHelper.java:51)
E/AndroidRuntime(26804): 	at androidx.appcompat.widget.AppCompatTextView.<init>(AppCompatTextView.java:105)
E/AndroidRuntime(26804): 	at androidx.appcompat.widget.AppCompatTextView.<init>(AppCompatTextView.java:95)
E/AndroidRuntime(26804): 	at androidx.appcompat.app.AppCompatViewInflater.createTextView(AppCompatViewInflater.java:194)
E/AndroidRuntime(26804): 	at androidx.appcompat.app.AppCompatViewInflater.createView(AppCompatViewInflater.java:115)
E/AndroidRuntime(26804): 	at androidx.appcompat.app.AppCompatDelegateImpl.createView(AppCompatDelegateImpl.java:1551)
E/AndroidRuntime(26804): 	at androidx.appcompat.app.AppCompatDelegateImpl.onCreateView(AppCompatDelegateImpl.java:1602)
E/AndroidRuntime(26804): 	at android.view.LayoutInflater$FactoryMerger.onCreateView(LayoutInflater.java:242)
E/AndroidRuntime(26804): 	at android.view.LayoutInflater.tryCreateView(LayoutInflater.java:1061)
E/AndroidRuntime(26804): 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:997)
E/AndroidRuntime(26804): 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:961)
E/AndroidRuntime(26804): 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1123)
E/AndroidRuntime(26804): 	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1084)
E/AndroidRuntime(26804): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:682)
E/AndroidRuntime(26804): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:534)
E/AndroidRuntime(26804): 	at com.thegrizzlylabs.geniusscan.sdk.ui.CameraFragment.onCreateView(CameraFragment.java:56)
E/AndroidRuntime(26804): 	at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2600)
E/AndroidRuntime(26804): 	at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:881)
E/AndroidRuntime(26804): 	at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1238)
E/AndroidRuntime(26804): 	at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1303)
E/AndroidRuntime(26804): 	at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:439)
E/AndroidRuntime(26804): 	at androidx.fragment.app.FragmentManagerImpl.executeOps(FragmentManagerImpl.java:2079)
E/AndroidRuntime(26804): 	at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManagerImpl.java:1869)
E/AndroidRuntime(26804): 	at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManagerImpl.java:1824)
E/AndroidRuntime(26804): 	at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManagerImpl.java:1727)
E/AndroidRuntime(26804): 	at androidx.fragment.app.FragmentManagerImpl.dispatchStateChange(FragmentManagerImpl.java:2663)
E/AndroidRuntime(26804): 	at androidx.fragment.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManagerImpl.java:2613)
E/AndroidRuntime(26804): 	at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:246)
E/AndroidRuntime(26804): 	at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:542)
E/AndroidRuntime(26804): 	at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:210)
E/AndroidRuntime(26804): 	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1433)
E/AndroidRuntime(26804): 	at android.app.Activity.performStart(Activity.java:7980)
E/AndroidRuntime(26804): 	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3655)
E/AndroidRuntime(26804): 	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
E/AndroidRuntime(26804): 	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
E/AndroidRuntime(26804): 	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
E/AndroidRuntime(26804): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
E/AndroidRuntime(26804): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2270)
E/AndroidRuntime(26804): 	at android.os.Handler.dispatchMessage(Handler.java:107)
E/AndroidRuntime(26804): 	at android.os.Looper.loop(Looper.java:237)
E/AndroidRuntime(26804): 	at android.app.ActivityThread.main(ActivityThread.java:8125)
E/AndroidRuntime(26804): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(26804): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
E/AndroidRuntime(26804): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
```

Working environment: 

```
Flutter 1.22.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 84f3d28555 (3 days ago) • 2020-10-15 16:26:19 -0700
Engine • revision b8752bbfff
Tools • Dart 2.10.2
```

**Comment by Abhijeet-sonkar** [comment]
Can I work on this issue?

**Comment by jamesbrian0323** [comment]
Hi, @Abhijeet-sonkar 
Sure, please let me know if you need other information.

**Comment by rkotzy** [comment]
Hi 👋. Are you able to provide more information about how to reproduce this issue and what is triggering the crash with Purchases Flutter?

**Comment by jamesbrian0323** [comment]
Hi, all.
I am getting error when I call below function.
```
FlutterGeniusScan.scanWithConfiguration({
          'source': 'camera',
          'multiPage': true,
        });
```

**Comment by vegaro** [comment]
This error is normally due to duplicate androidx libs, we used it internally and that other dependency `flutter_genius_scan` must also be another version of androidx. 

I removed the androidx dependency in the latest `purchases_flutter` version. Can you try with `purchases_flutter` 1.4.0?

**Comment by jamesbrian0323** [comment]
Hi, @vegaro.
Thanks for your reply.
I tried with latest version 1.4.0 and got same error.

**Comment by Boldman7** [comment]
Hi, @jamesbrian0323 
I think the reason is the setting of androidx.
Please check if you set the config for the androidx in android/build.gradle.
Maybe you need to disable the config.
I hope you fix the issue.

**Comment by jamesbrian0323** [comment]
Thanks, @Boldman7 
I fixed the issue following you.
