### ISSUE TITLE
Sometimes payment information doesn't come from revenue cat server

### ISSUE THREAD

**Issue by NarHakobyan** [RevenueCat/purchases-flutter#156]
**Describe the bug**
This issue appears time by time in crashlitics.

Non-fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError: NoSuchMethodError: The getter 'annual' was called on null.
Receiver: null
Tried calling: annual. Error thrown Instance of 'ErrorDescription'.
       at _SubscriptionDialogState.build(_SubscriptionDialogState.java:168)
       at StatefulElement.build(StatefulElement.java:4744)
       at ComponentElement.performRebuild(ComponentElement.java:4627)
       at StatefulElement.performRebuild(StatefulElement.java:4800)
       at Element.rebuild(Element.java:4343)
       at ComponentElement._firstBuild(ComponentElement.java:4606)
       at StatefulElement._firstBuild(StatefulElement.java:4791)
       at ComponentElement.mount(ComponentElement.java:4601)
       at Element.inflateWidget(Element.java:3569)
       at Element.updateChild(Element.java:3327)
       at ComponentElement.performRebuild(ComponentElement.java:4652)
       at Element.rebuild(Element.java:4343)
       at ComponentElement._firstBuild(ComponentElement.java:4606)
       at ComponentElement.mount(ComponentElement.java:4601)
       at Element.inflateWidget(Element.java:3569)
       at Element.updateChild(Element.java:3327)
       at ComponentElement.performRebuild(ComponentElement.java:4652)
       at Element.rebuild(Element.java:4343)
       at ComponentElement._firstBuild(ComponentElement.java:4606)
       at ComponentElement.mount(ComponentElement.java:4601)
       at Element.inflateWidget(Element.java:3569)
       at Element.updateChild(Element.java:3327)
       at ComponentElement.performRebuild(ComponentElement.java:4652)
       at Element.rebuild(Element.java:4343)
       at ComponentElement._firstBuild(ComponentElement.java:4606)
       at ComponentElement.mount(ComponentElement.java:4601)
       at Element.inflateWidget(Element.java:3569)
       at Element.updateChild(Element.java:3327)
       at SingleChildRenderObjectElement.mount(SingleChildRenderObjectElement.java:6118)
       at Element.inflateWidget(Element.java:3569)
       at Element.updateChild(Element.java:3327)
       at ComponentElement.performRebuild(ComponentElement.java:4652)
       at Element.rebuild(Element.java:4343)
       at ComponentElement._firstBuild(ComponentElement.java:4606)
       at ComponentElement.mount(ComponentElement.java:4601)
       at Element.inflateWidget(Element.java:3569)
       at Element.updateChild(Element.java:3327)
       at SingleChildRenderObjectElement.mount(SingleChildRenderObjectElement.java:6118)
       at Element.inflateWidget(Element.java:3569)
       at Element.updateChild(Element.java:3327)
       at ComponentElement.performRebuild(ComponentElement.java:4652)
       at Element.rebuild(Element.java:4343)
       at ComponentElement._firstBuild(ComponentElement.java:4606)
       at ComponentElement.mount(ComponentElement.java:4601)
       at Element.inflateWidget(Element.java:3569)
       at Element.updateChild(Element.java:3327)
       at SingleChildRenderObjectElement.mount(SingleChildRenderObjectElement.java:6118)
       at Element.inflateWidget(Element.java:3569)
       at Element.updateChild(Element.java:3327)
       at SingleChildRenderObjectElement.mount(SingleChildRenderObjectElement.java:6118)
       at Element.inflateWidget(Element.java:3569)
       at Element.updateChild(Element.java:3327)
       at ComponentElement.performRebuild(ComponentElement.java:4652)
       at StatefulElement.performRebuild(StatefulElement.java:4800)
       at Element.rebuild(Element.java:4343)
       at ComponentElement._firstBuild(ComponentElement.java:4606)
       at StatefulElement._firstBuild(StatefulElement.java:4791)
       at ComponentElement.mount(ComponentElement.java:4601)
       at Element.inflateWidget(Element.java:3569)
       at Element.updateChild(Element.java:3327)
       at SingleChildRenderObjectElement.mount(SingleChildRenderObjectElement.java:6118)
       at Element.inflateWidget(Element.java:3569)
       at Element.updateChild(Element.java:3327)
       at ComponentElement.performRebuild(ComponentElement.java:4652)
       at StatefulElement.performRebuild(StatefulElement.java:4800)
       at Element.rebuild(Element.java:4343)
       at ComponentElement._firstBuild(ComponentElement.java:4606)
       at StatefulElement._firstBuild(StatefulElement.java:4791)
       at ComponentElement.mount(ComponentElement.java:4601)
       at Element.inflateWidget(Element.java:3569)
       at Element.updateChild(Element.java:3327)
       at SingleChildRenderObjectElement.mount(SingleChildRenderObjectElement.java:6118)
       at Element.inflateWidget(Element.java:3569)
       at Element.updateChild(Element.java:3327)
       at ComponentElement.performRebuild(ComponentElement.java:4652)
       at Element.rebuild(Element.java:4343)
       at ComponentElement._firstBuild(ComponentElement.java:4606)
       at ComponentElement.mount(ComponentElement.java:4601)
       at Element.inflateWidget(Element.java:3569)
       at Element.updateChild(Element.java:3327)
       at SingleChildRenderObjectElement.mount(SingleChildRenderObjectElement.java:6118)
       at Element.inflateWidget(Element.java:3569)
       at Element.updateChild(Element.java:3327)
       at ComponentElement.performRebuild(ComponentElement.java:4652)
       at StatefulElement.performRebuild(StatefulElement.java:4800)
       at Element.rebuild(Element.java:4343)
       at ComponentElement._firstBuild(ComponentElement.java:4606)
       at StatefulElement._firstBuild(StatefulElement.java:4791)
       at ComponentElement.mount(ComponentElement.java:4601)
       at Element.inflateWidget(Element.java:3569)
       at Element.updateChild(Element.java:3327)
       at ComponentElement.performRebuild(ComponentElement.java:4652)
       at Element.rebuild(Element.java:4343)
       at ComponentElement._firstBuild(ComponentElement.java:4606)
       at ComponentElement.mount(ComponentElement.java:4601)
       at Element.inflateWidget(Element.java:3569)
       at Element.updateChild(Element.java:3327)
       at ComponentElement.performRebuild(ComponentElement.java:4652)
       at StatefulElement.performRebuild(StatefulElement.java:4800)
       at Element.rebuild(Element.java:4343)
       at ComponentElement._firstBuild(ComponentElement.java:4606)
       at StatefulElement._firstBuild(StatefulElement.java:4791)
       at ComponentElement.mount(ComponentElement.java:4601)
       at Element.inflateWidget(Element.java:3569)
       at Element.updateChild(Element.java:3327)
       at ComponentElement.performRebuild(ComponentElement.java:4652)
       at Element.rebuild(Element.java:4343)
       at ComponentElement._firstBuild(ComponentElement.java:4606)
       at ComponentElement.mount(ComponentElement.java:4601)
       at Element.inflateWidget(Element.java:3569)
       at Element.updateChild(Element.java:3327)
       at SingleChildRenderObjectElement.mount(SingleChildRenderObjectElement.java:6118)
       at Element.inflateWidget(Element.java:3569)
       at Element.updateChild(Element.java:3327)
       at ComponentElement.performRebuild(ComponentElement.java:4652)
       at Element.rebuild(Element.java:4343)
       at ComponentElement._firstBuild(ComponentElement.java:4606)
       at ComponentElement.mount(ComponentElement.java:4601)
       at Element.inflateWidget(Element.java:3569)
       at Element.updateChild(Element.java:3327)
       at ComponentElement.performRebuild(ComponentElement.java:4652)
       at StatefulElement.performRebuild(StatefulElement.java:4800)
       at Element.rebuild(Element.java:4343)
       at ComponentElement._firstBuild(ComponentElement.java:4606)
       at StatefulElement._firstBuild(StatefulElement.java:4791)
       at ComponentElement.mount(ComponentElement.java:4601)
       at Element.inflateWidget(Element.java:3569)
       at Element.updateChild(Element.java:3327)
       at SingleChildRenderObjectElement.mount(SingleChildRenderObjectElement.java:6118)
       at Element.inflateWidget(Element.java:3569)
       at Element.updateChild(Element.java:3327)
       at ComponentElement.performRebuild(ComponentElement.java:4652)
       at Element.rebuild(Element.java:4343)
       at ComponentElement._firstBuild(ComponentElement.java:4606)
       at ComponentElement.mount(ComponentElement.java:4601)
       at Element.inflateWidget(Element.java:3569)
       at Element.updateChild(Element.java:3327)
       at ComponentElement.performRebuild(ComponentElement.java:4652)
       at Element.rebuild(Element.java:4343)
       at ComponentElement._firstBuild(ComponentElement.java:4606)
       at ComponentElement.mount(ComponentElement.java:4601)
       at Element.inflateWidget(Element.java:3569)
       at Element.updateChild(Element.java:3327)
       at ComponentElement.performRebuild(ComponentElement.java:4652)
       at StatefulElement.performRebuild(StatefulElement.java:4800)
       at Element.rebuild(Element.java:4343)
       at ComponentElement._firstBuild(ComponentElement.java:4606)
       at StatefulElement._firstBuild(StatefulElement.java:4791)
       at ComponentElement.mount(ComponentElement.java:4601)
       at Element.inflateWidget(Element.java:3569)
       at Element.updateChild(Element.java:3327)
       at RenderObjectElement.updateChildren(RenderObjectElement.java:5705)
       at MultiChildRenderObjectElement.update(MultiChildRenderObjectElement.java:6246)
       at Element.updateChild(Element.java:3314)
       at ComponentElement.performRebuild(ComponentElement.java:4652)
       at StatefulElement.performRebuild(StatefulElement.java:4800)
       at Element.rebuild(Element.java:4343)
       at StatefulElement.update(StatefulElement.java:4832)
       at Element.updateChild(Element.java:3314)
       at ComponentElement.performRebuild(ComponentElement.java:4652)
       at Element.rebuild(Element.java:4343)
       at ProxyElement.update(ProxyElement.java:4987)
       at _InheritedNotifierElement.update(_InheritedNotifierElement.java:183)
       at Element.updateChild(Element.java:3314)
       at SingleChildRenderObjectElement.update(SingleChildRenderObjectElement.java:6125)
       at Element.updateChild(Element.java:3314)
       at ComponentElement.performRebuild(ComponentElement.java:4652)
       at StatefulElement.performRebuild(StatefulElement.java:4800)
       at Element.rebuild(Element.java:4343)
       at StatefulElement.update(StatefulElement.java:4832)
       at Element.updateChild(Element.java:3314)
       at SingleChildRenderObjectElement.update(SingleChildRenderObjectElement.java:6125)
       at Element.updateChild(Element.java:3314)
       at SingleChildRenderObjectElement.update(SingleChildRenderObjectElement.java:6125)
       at Element.updateChild(Element.java:3314)
       at ComponentElement.performRebuild(ComponentElement.java:4652)
       at Element.rebuild(Element.java:4343)
       at StatelessElement.update(StatelessElement.java:4708)
       at Element.updateChild(Element.java:3314)
       at ComponentElement.performRebuild(ComponentElement.java:4652)
       at Element.rebuild(Element.java:4343)
       at ProxyElement.update(ProxyElement.java:4987)
       at Element.updateChild(Element.java:3314)
       at ComponentElement.performRebuild(ComponentElement.java:4652)
       at StatefulElement.performRebuild(StatefulElement.java:4800)
       at Element.rebuild(Element.java:4343)
       at BuildOwner.buildScope(BuildOwner.java:2730)
       at WidgetsBinding.drawFrame(WidgetsBinding.java:913)
       at RendererBinding._handlePersistentFrameCallback(RendererBinding.java:302)
       at SchedulerBinding._invokeFrameCallback(SchedulerBinding.java:1117)
       at SchedulerBinding.handleDrawFrame(SchedulerBinding.java:1055)
       at SchedulerBinding._handleDrawFrame(SchedulerBinding.java:971)

**Comment by vegaro** [comment]
It looks like you are accessing the `annual` package on a null offering. `offerings.current` can be null, when there is some issue loading the products, so make sure to add a null check before accessing it. We are going to add null safety support soon, which will reduce these sort of errors.

**Comment by NarHakobyan** [comment]
@vegaro offering exists, and it's working most of the time, sometimes it's just throwing an error

**Comment by vegaro** [comment]
Are you adding a null check before accessing the offering?

**Comment by NarHakobyan** [comment]
why am I need to add a null check if offerings exist on every platform?

**Comment by vegaro** [comment]
Your product identifiers are set in RevenueCat, but the actual products that your users purchase can only be retrieved directly from Apple/Google. Because this communication happens between your app and the stores, RevenueCat doesn't have any visibility into the API requests. If that communication between RevenueCat and Apple/Google fails, RevenueCat  SDK won't be able to fetch the products, and the offerings will be null (even if they are configured in the dashboard). You can null check the offerings to make sure they have loaded correctly.

**Comment by NarHakobyan** [comment]
Okay, thanks for answering, I thought takes care of such problems.
