### ISSUE TITLE
CocoaPods: PurchasesHybridCommon required a higher minimum deployment target

### ISSUE THREAD

**Issue by muhlba91** [RevenueCat/purchases-flutter#189]
- [X] I have updated Purchases SDK to the latest version
- [X] I have read the [Contribution Guidelines](https://github.com/RevenueCat/purchases-flutter/blob/develop/CONTRIBUTING.md)
- [X] I have read the [Help Center](https://support.revenuecat.com/hc/en-us)
- [X] I have read [docs.revenuecat.com](https://docs.revenuecat.com/)
- [X] I have searched for [existing Github issues](https://github.com/RevenueCat/purchases-flutter/issues)

**Describe the bug**
1. Environment
   1. Output of `flutter doctor`
   2. How widespread is the issue. Percentage of devices affected.
2. [Debug logs](https://docs.revenuecat.com/docs/debugging) that reproduce the issue
3. Steps to reproduce, with a description of expected vs. actual behavior
4. **Other information** (e.g. stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc.)

I am having a macOS app and updated `purchases_flutter` from `3.0.0` to `3.2.1`. When building the app, CocoaPods receive an error that the deployment target (set to `11` in all configuration files) is too low. In the docs, the required minimum is `10.12`.

Environment: ARM64/M1 macOS
Deployment Target: `11`
macOS version: `11.3 (beta)`
Flutter version: `2.2.0-10.1.pre`, channel `dev`

`flutter doctor` output:
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, 2.2.0-10.1.pre, on macOS 11.3 20E5231a darwin-arm, locale en-AT)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio
[✓] Connected device (2 available)

• No issues found!
```

`flutter run` output:
```
Launching lib/main.dart on macOS in debug mode...
Running pod install...                                           1,995ms
CocoaPods' output:
↳
      Preparing

    Analyzing dependencies

    Inspecting targets to integrate
      Using `ARCHS` setting to build architectures of target `Pods-Runner`: (``)

    Finding Podfile changes
      - FirebaseFirestore
      - FlutterMacOS
      - firebase_core
      - firebase_crashlytics
      - firebase_remote_config
      - package_info
      - path_provider_macos
      - purchases_flutter
      - shared_preferences_macos
      - url_launcher_macos

    Fetching external sources
    -> Pre-downloading: `FirebaseFirestore` from `https://github.com/invertase/firestore-ios-sdk-frameworks.git`, tag `7.5.0`
      > Copying FirebaseFirestore from
      `/Users/daniel/Library/Caches/CocoaPods/Pods/External/FirebaseFirestore/d4c580a9238c73780c213eb24eb6ce35` to
      `Pods/FirebaseFirestore`
    -> Fetching podspec for `FlutterMacOS` from `Flutter/ephemeral`
    -> Fetching podspec for `firebase_core` from `Flutter/ephemeral/.symlinks/plugins/firebase_core/macos`
    firebase_core: Using Firebase SDK version '7.3.0' defined in 'firebase_core'
    -> Fetching podspec for `firebase_crashlytics` from `Flutter/ephemeral/.symlinks/plugins/firebase_crashlytics/macos`
    firebase_crashlytics: Using Firebase SDK version '7.3.0' defined in 'firebase_core'
    -> Fetching podspec for `firebase_remote_config` from `Flutter/ephemeral/.symlinks/plugins/firebase_remote_config/macos`
    firebase_remote_config: Using Firebase SDK version '7.3.0' defined in 'firebase_core'
    -> Fetching podspec for `package_info` from `Flutter/ephemeral/.symlinks/plugins/package_info/macos`
    -> Fetching podspec for `path_provider_macos` from `Flutter/ephemeral/.symlinks/plugins/path_provider_macos/macos`
    -> Fetching podspec for `purchases_flutter` from `Flutter/ephemeral/.symlinks/plugins/purchases_flutter/macos`
    -> Fetching podspec for `shared_preferences_macos` from `Flutter/ephemeral/.symlinks/plugins/shared_preferences_macos/macos`
    -> Fetching podspec for `url_launcher_macos` from `Flutter/ephemeral/.symlinks/plugins/url_launcher_macos/macos`

    Resolving dependencies of `Podfile`
      CDN: trunk Relative path: CocoaPods-version.yml exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: all_pods_versions_0_3_5.txt exists! Returning local because checking is only perfomed in repo
      update
      CDN: trunk Relative path: Specs/0/3/5/Firebase/7.8.1/Firebase.podspec.json exists! Returning local because checking is only
      perfomed in repo update
      CDN: trunk Relative path: Specs/0/3/5/Firebase/7.3.0/Firebase.podspec.json exists! Returning local because checking is only
      perfomed in repo update
      CDN: trunk Relative path: Specs/0/3/5/Firebase/7.3.0/Firebase.podspec.json exists! Returning local because checking is only
      perfomed in repo update
      CDN: trunk Relative path: all_pods_versions_9_a_d.txt exists! Returning local because checking is only perfomed in repo
      update
      CDN: trunk Relative path: Specs/9/a/d/PurchasesHybridCommon/1.6.1/PurchasesHybridCommon.podspec.json exists! Returning local
      because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/0/3/5/Firebase/7.3.0/Firebase.podspec.json exists! Returning local because checking is only
      perfomed in repo update
    [!] CocoaPods could not find compatible versions for pod "PurchasesHybridCommon":
      In snapshot (Podfile.lock):
        PurchasesHybridCommon (= 1.5.0)

      In Podfile:
        purchases_flutter (from `Flutter/ephemeral/.symlinks/plugins/purchases_flutter/macos`) was resolved to 3.2.1, which
        depends on
          PurchasesHybridCommon (= 1.6.2)

    Specs satisfying the `PurchasesHybridCommon (= 1.5.0), PurchasesHybridCommon (= 1.6.2)` dependency were found, but they
    required a higher minimum deployment target.

    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:328:in `raise_error_unless_state'
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:310:in `block in unwind_for_conflict'
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:308:in `tap'
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:308:in `unwind_for_conflict'
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:257:in `process_topmost_state'
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:182:in `resolve'
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolver.rb:43:in `resolve'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/resolver.rb:94:in `resolve'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer/analyzer.rb:1074:in `block in resolve_dependencies'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/user_interface.rb:64:in `section'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer/analyzer.rb:1072:in `resolve_dependencies'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer/analyzer.rb:124:in `analyze'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:414:in `analyze'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:239:in `block in resolve_dependencies'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/user_interface.rb:64:in `section'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:238:in `resolve_dependencies'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:160:in `install!'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/command/install.rb:52:in `run'
    /Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/command.rb:52:in `run'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/bin/pod:55:in `<top (required)>'
    /usr/local/bin/pod:23:in `load'
    /usr/local/bin/pod:23:in `<main>'

Exception: Error running pod install
```

**Additional context**
N/A

**Comment by aboedo** [comment]
hi! the minimum deployment target for all our pods is 9.0 for iOS, and 10.12 for macOS, as defined in the following files: 

https://github.com/RevenueCat/purchases-flutter/blob/develop/ios/purchases_flutter.podspec#L19
https://github.com/RevenueCat/purchases-flutter/blob/develop/macos/purchases_flutter.podspec#L20
https://github.com/RevenueCat/purchases-hybrid-common/blob/develop/PurchasesHybridCommon.podspec#L21
https://github.com/RevenueCat/purchases-ios/blob/develop/Purchases.podspec#L19
https://github.com/RevenueCat/purchases-ios/blob/develop/PurchasesCoreSwift.podspec#L19

You can still get this message if you haven't defined the deployment target in the Podfile itself, and you'd have to make sure that the deployment target is defined for both the iOS and the macOS target. 

Have you already set the deployment target in the macOS target?

**Comment by muhlba91** [comment]
Yes, my Podfile contains: `platform :osx, '11'` and `MACOSX_DEPLOYMENT_TARGET = 11.0;` is set in all target configurations.

Same in my iOS configuration. Podfile: `platform :ios, '14.1'`; `IPHONEOS_DEPLOYMENT_TARGET = '14.1';'

**Comment by aboedo** [comment]
would you mind sharing your Podfile in that case? It's the only way to debug what's going on. You can also try deleting the Podfile.lock file and running pod install again, in case there's anything wrong with the generated `.lock` file

**Comment by muhlba91** [comment]
sure, find attached the podfile and also pubspec. (seems like i can only upload .txt files 😄)
[Podfile.txt](https://github.com/RevenueCat/purchases-flutter/files/6352096/Podfile.txt)
[pubspec.txt](https://github.com/RevenueCat/purchases-flutter/files/6352097/pubspec.txt)

i'm also starting to think this might be an issue with working on ARM64/M1. unfortunately, i'm having a hard time getting hold on a non-M1 atm to check.

**Comment by aboedo** [comment]
🤔 

I think there's a chance that Flutter is actually overriding your macOS deployment target, probably in `flutter_additional_macos_build_settings`. 

If that's the case, perhaps a workaround could be adding 

```ruby
target.build_configurations.each do |config|
  config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.2'
end
```
right after the `flutter_additional_macos_build_settings` line in your Podfile. 

If that solves it, we can report that to the Flutter team and figure out a better workaround for everyone

**Comment by muhlba91** [comment]
Awesome! 🎉 This and removing the old `Podfile.lock` worked to have all dependencies resolving correctly.

**Comment by aboedo** [comment]
closing this issue as solved, let us know if you run into anything else!
