### ISSUE TITLE
Error runned on android with  flutter fragment

### ISSUE THREAD

**Issue by audiserg** [RevenueCat/purchases-flutter#271]
E/flutter: [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: MissingPluginException(No implementation found for method setupPurchases on channel purchases_flutter)
    #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:154:7)
    <asynchronous suspension>
    #1      Purchases.setup (package:purchases_flutter/purchases_flutter.dart:47:12)
    <asynchronous suspension>
    #2      initPlatformState (package:flutter_ui/subscription/revenue.dart:6:3)
    <asynchronous suspension>

Flutter run in fragment. Library can't find no one method

___________________________________________________________________
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.5.3, on Mac OS X 10.15.7 19H1217 darwin-x64,
    locale ru-RU)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✗] Xcode - develop for iOS and macOS
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS
      development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -runFirstLaunch
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install see
      https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] VS Code (version 1.62.0)
[✓] Connected device (2 available)

! Doctor found issues in 1 category.

**Comment by audiserg** [comment]
I found that problem solved in this thread https://github.com/flutter/flutter/issues/66230 . Reason: FlutterFragment not registering GeneratedPluginRegistrant
