### ISSUE TITLE
Purchases.purchaseProduct and Purchases.purchasePackage returns Unhandled Exception

### ISSUE THREAD

**Issue by yarmel** [RevenueCat/purchases-flutter#305]
Purchases stop working after updating to the latest version. Issue detected in version 3.9.0+

```
[Purchases] - DEBUG: ℹ️ applicationDidBecomeActive
[Purchases] - DEBUG: ℹ️ API request completed with status: POST /v1/receipts 200
[Purchases] - DEBUG: ℹ️ Serial request done: POST /receipts, 0 requests left in the queue
[Purchases] - DEBUG: ℹ️ Sending updated PurchaserInfo to delegate.
[Purchases] - DEBUG: 💰 Finishing transaction Oct640Pkg 1000000951821687 ((null))
[VERBOSE-2:ui_dart_state.cc(209)] Unhandled Exception: type '_InternalLinkedHashMap<Object?, Object?>' is not a subtype of type 'Map<String, dynamic>'
#0      Purchases.purchaseProduct (package:purchases_flutter/purchases_flutter.dart:199:43)
<asynchronous suspension>
#1      _CoinExchangeState._onProductPurchase (package:octopoos/ui/screens/profile/widgets/coin_exchange.dart:85:7)
<asynchronous suspension>
[Purchases] - DEBUG: ℹ️ PaymentQueue removedTransaction: Oct640Pkg 1000000951821687 ((null) (null)) (null) - 1
```

**Comment by vegaro** [comment]
Hi! Sorry about that. We just pushed 3.9.2 that fixes the problem. The original bug report https://github.com/RevenueCat/purchases-flutter/issues/300 has more information.
