### ISSUE TITLE
Android crash when getting products/offerings

### ISSUE THREAD

**Issue by patchimou** [RevenueCat/purchases-flutter#89]
My android app crash with the following stacktrace:

````
java.lang.NoSuchMethodError: No virtual method getIntroductoryPriceCycles()Ljava/lang/String; in class Lcom/android/billingclient/api/SkuDetails; or its super classes (declaration of 'com.android.billingclient.api.SkuDetails' appears in /data/app/com.twipe.travelust-2/base.apk)
E/AndroidRuntime(26721): 	at com.revenuecat.purchases.common.MappersKt.mapIntroPriceDeprecated(mappers.kt:121)
E/AndroidRuntime(26721): 	at com.revenuecat.purchases.common.MappersKt.map(mappers.kt:54)
E/AndroidRuntime(26721): 	at com.revenuecat.purchases.common.MappersKt.map(mappers.kt:82)
E/AndroidRuntime(26721): 	at com.revenuecat.purchases.common.CommonKt$getProductInfo$onReceived$1.invoke(common.kt:70)
E/AndroidRuntime(26721): 	at com.revenuecat.purchases.common.CommonKt$getProductInfo$onReceived$1.invoke(common.kt)
E/AndroidRuntime(26721): 	at com.revenuecat.purchases.ListenerConversionsKt$getSkusResponseListener$1.onReceived(listenerConversions.kt:38)
E/AndroidRuntime(26721): 	at com.revenuecat.purchases.Purchases$getSkus$1$1.invoke(Purchases.kt:797)
E/AndroidRuntime(26721): 	at com.revenuecat.purchases.Purchases$getSkus$1$1.invoke(Purchases.kt:53)
E/AndroidRuntime(26721): 	at com.revenuecat.purchases.Purchases.dispatch(Purchases.kt:1069)
E/AndroidRuntime(26721): 	at com.revenuecat.purchases.Purchases.access$dispatch(Purchases.kt:53)
E/AndroidRuntime(26721): 	at com.revenuecat.purchases.Purchases$getSkus$1.invoke(Purchases.kt:796)
E/AndroidRuntime(26721): 	at com.revenuecat.purchases.Purchases$getSkus$1.invoke(Purchases.kt:53)
E/AndroidRuntime(26721): 	at com.revenuecat.purchases.BillingWrapper$querySkuDetailsAsync$1$1.onSkuDetailsResponse(BillingWrapper.kt:147)
E/AndroidRuntime(26721): 	at com.android.billingclient.api.zzj.run(com.android.billingclient:billing@@3.0.0:8)
E/AndroidRuntime(26721): 	at android.os.Handler.handleCallback(Handler.java:739)
E/AndroidRuntime(26721): 	at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime(26721): 	at android.os.Looper.loop(Looper.java:148)
E/AndroidRuntime(26721): 	at android.app.ActivityThread.main(ActivityThread.java:5461)
E/AndroidRuntime(26721): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(26721): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
E/AndroidRuntime(26721): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
````
I enabled `setDebugLogsEnabled(true)` and I can see my product being fetched properly in the logs.
My product is not a subscription, but an inapp type.

flutter: 1.17.5
android: 6.0.1

**Comment by patchimou** [comment]
I Solved it by removing the billingclient from the build gradle

**Comment by rdcoder33** [comment]
> I Solved it by removing the billingclient from the build gradle

Hey there patchimou!
I am getting the same error, can you please tell me what you mean by billingclient in build.gradle?

**Comment by patchimou** [comment]
@rdcoder33 
```
dependencies {
    implementation 'com.android.billingclient:billing:3.0.0' <-- to remove
}
```

**Comment by AbhayDeligence** [comment]
After removing the billingclient google play console gives error.

We've detected that this app uses an unsupported version of Play Billing. Please upgrade to Billing Library version 4 or newer to publish this app.

Please provide the solution of this.
