### ISSUE TITLE
StrictMode policy violation: android.os.strictmode.NonSdkApiUsedViolation:

### ISSUE THREAD

**Issue by robertoltrocha** [RevenueCat/purchases-flutter#94]
Hi,
In the publication of the Play Store we are receiving alerts about incompability.

purchases_flutter: ^1.2.1
Android: SDK 30

```
[√] Flutter (Channel stable, 1.20.2, on Microsoft Windows [versÃ£o 10.0.19041.508], locale pt-BR)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.0-rc1)
[√] Android Studio (version 4.0)
[!] VS Code, 64-bit edition (version 1.49.0)
    X Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter
[√] Connected device (1 available)
```

```
StrictMode policy violation: android.os.strictmode.NonSdkApiUsedViolation: Ljava/net/Socket;->impl:Ljava/net/SocketImpl;
	at android.os.StrictMode.lambda$static$1(StrictMode.java:428)
	at android.os.-$$Lambda$StrictMode$lu9ekkHJ2HMz0jd3F8K8MnhenxQ.accept(Unknown Source:2)
	at java.lang.Class.getDeclaredField(Native Method)
	at com.google.android.gms.org.conscrypt.Platform.getFileDescriptor(:com.google.android.gms@202116028@20.21.16 (100400-315540369):1)
	at com.google.android.gms.org.conscrypt.ConscryptFileDescriptorSocket$SSLInputStream.read(:com.google.android.gms@202116028@20.21.16 (100400-315540369):6)
	at com.android.okhttp.okio.Okio$2.read(Okio.java:136)
	at com.android.okhttp.okio.AsyncTimeout$2.read(AsyncTimeout.java:211)
	at com.android.okhttp.okio.RealBufferedSource.indexOf(RealBufferedSource.java:306)
	at com.android.okhttp.okio.RealBufferedSource.indexOf(RealBufferedSource.java:300)
	at com.android.okhttp.okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:196)
	at com.android.okhttp.internal.http.Http1xStream.readResponse(Http1xStream.java:186)
	at com.android.okhttp.internal.http.Http1xStream.readResponseHeaders(Http1xStream.java:127)
	at com.android.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:737)
	at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:609)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:471)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:407)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:538)
	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getResponseCode(DelegatingHttpsURLConnection.java:105)
	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:26)
	at com.google.firebase.perf.network.zzf.getInputStream(Unknown Source:7)
	at com.google.firebase.perf.network.zzc.getInputStream(Unknown Source:2)
	at com.revenuecat.purchases.HTTPClient.getInputStream(Unknown Source:0)
	at com.revenuecat.purchases.HTTPClient.performRequest(Unknown Source:51)
	at com.revenuecat.purchases.Backend$getPurchaserInfo$call$1.call(Unknown Source:38)
	at com.revenuecat.purchases.Dispatcher$AsyncCall.run(Unknown Source:0)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)
```

```
StrictMode policy violation: android.os.strictmode.NonSdkApiUsedViolation: Ljava/net/Socket;->impl:Ljava/net/SocketImpl;
	at android.os.StrictMode.lambda$static$1(StrictMode.java:428)
	at android.os.-$$Lambda$StrictMode$lu9ekkHJ2HMz0jd3F8K8MnhenxQ.accept(Unknown Source:2)
	at java.lang.Class.getDeclaredField(Native Method)
	at com.google.android.gms.org.conscrypt.Platform.getFileDescriptor(:com.google.android.gms@202116028@20.21.16 (100400-315540369):1)
	at com.google.android.gms.org.conscrypt.ConscryptFileDescriptorSocket$SSLInputStream.read(:com.google.android.gms@202116028@20.21.16 (100400-315540369):6)
	at com.android.okhttp.okio.Okio$2.read(Okio.java:136)
	at com.android.okhttp.okio.AsyncTimeout$2.read(AsyncTimeout.java:211)
	at com.android.okhttp.okio.RealBufferedSource.read(RealBufferedSource.java:50)
	at com.android.okhttp.internal.http.Http1xStream$FixedLengthSource.read(Http1xStream.java:393)
	at com.android.okhttp.okio.RealBufferedSource$1.read(RealBufferedSource.java:371)
	at com.google.firebase.perf.network.zzb.read(Unknown Source:2)
	at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:288)
	at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:351)
	at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:180)
	at java.io.InputStreamReader.read(InputStreamReader.java:184)
	at java.io.BufferedReader.fill(BufferedReader.java:172)
	at java.io.BufferedReader.readLine(BufferedReader.java:335)
	at java.io.BufferedReader.readLine(BufferedReader.java:400)
	at com.revenuecat.purchases.HTTPClient.readFully(Unknown Source:5)
	at com.revenuecat.purchases.HTTPClient.readFully(Unknown Source:4)
	at com.revenuecat.purchases.HTTPClient.performRequest(Unknown Source:96)
	at com.revenuecat.purchases.Backend$getOfferings$call$1.call(Unknown Source:15)
	at com.revenuecat.purchases.Dispatcher$AsyncCall.run(Unknown Source:0)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)

```

**Comment by aboedo** [comment]
Hi @robertoltrocha, thanks for reporting! 

It looks like `java/io/BufferedReader`'s `readline()` has been hidden since API level 29 https://developer.android.com/distribute/best-practices/develop/restrictions-non-sdk-interfaces. 

This might not be an issue if you're not using `StrictMode` or you're targeting API level <= 28. We should update the corresponding code in [the android repo](https://github.com/RevenueCat/purchases-android/blob/develop/common/src/main/java/com/revenuecat/purchases/common/HTTPClient.kt#L40) and update the Flutter SDK with the changes. //cc @vegaro

**Comment by vegaro** [comment]
Hi @robertoltrocha . I tried setting StrictMode on and compile and target version to 30 and I can't seem to reproduce this. I looked into that `Platform.getFileDescriptor`, and it looks like they are doing some [reflection access ](https://github.com/google/conscrypt/blob/master/android/src/main/java/org/conscrypt/Platform.java#L94
) that is possibly triggering this alert.

I am going to close for now because it looks unrelated to RevenueCat, feel free to reopen if you have a way to reproduce it. Thanks!
